INSERT INTO PUBLIC.TENANT (TENANT_ID, COMPANY_NAME) VALUES('TENANT-165499', 'ENERGY');
INSERT INTO PUBLIC."USER" (USER_ID, TENANT_ID, EMAIL, NAME) VALUES('u2', 'TENANT-165499', 'u2@energy.com', 'user2');
INSERT INTO PUBLIC."USER" (USER_ID, TENANT_ID, EMAIL, NAME) VALUES('u1', 'TENANT-165499', 'u1@energy.com', 'user1');
INSERT INTO PUBLIC.ASSET (ASSET_ID, ASSET_NAME) VALUES('A', 'A');
INSERT INTO PUBLIC.WIFI (WIFI_ID, TENANT_ID,SSID,USERNAME,PASSWORD) VALUES('WIFI1', 'TENANT-165499','ssid1','username1','pwd1');

