CREATE TABLE PUBLIC.ASSET (
	ASSET_ID VARCHAR(100) NOT NULL,
	ASSET_NAME VARCHAR(100) NOT NULL,
	CONSTRAINT ASSET_PK PRIMARY KEY (ASSET_ID)
);

CREATE TABLE PUBLIC.TENANT (
	TENANT_ID VARCHAR(100) NOT NULL,
	COMPANY_NAME VARCHAR(100) NOT NULL,
	CONSTRAINT TENANT_PK PRIMARY KEY (TENANT_ID)
);

CREATE TABLE PUBLIC."USER" (
	USER_ID VARCHAR(100) NOT NULL,
	TENANT_ID VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	CONSTRAINT USER_PK PRIMARY KEY (USER_ID),
	CONSTRAINT USER_TENANT_FK FOREIGN KEY (TENANT_ID) REFERENCES PUBLIC.TENANT(TENANT_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PUBLIC.WIFI (
	WIFI_ID VARCHAR(100) NOT NULL,
	TENANT_ID VARCHAR(100) NOT NULL,
	SSID VARCHAR(100) NOT NULL,
	USERNAME VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	CONSTRAINT WIFI_PK PRIMARY KEY (WIFI_ID),
	CONSTRAINT WIFI_TENANT_FK FOREIGN KEY (TENANT_ID) REFERENCES PUBLIC.TENANT(TENANT_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
